Repository eoscostarica/guide.eoscostarica.io, pull requests merged in 2021-02, with the labels that each got.

#287 Delete package-lock.json
  package-lock.json
Labels: dependencies

#288 feat(readme): improve readme content
  README.md
  static/img/guide-page.png
Labels: WIP

#298 Fix/eosio dashboard
  docs/open-source-projects.md
Labels: WIP

#317 Docs/private network installation tutorial
  .gitignore
  docs/tutorials/private-network-installation.md
  static/img/private-network-installation-tutorial/initial-topology.png
  yarn.lock
Labels: Developer Guidelines, documentation

#327 docs: how to publish packages and other minor bug fixes
  docs/tutorials/how-to-publish-packages.md
  docs/tutorials/private-network-installation.md
  sidebars.js
  static/img/packages-publication/DeveloperSettings.png
  static/img/packages-publication/GenerateNewToken.png
  static/img/packages-publication/GenerateTokenButton.png
  static/img/packages-publication/GoToSettings.png
  static/img/packages-publication/PersonalAccessToken.png
  static/img/packages-publication/TokenScope.png
Labels: docs, documentation
