Repository eoscostarica/guide.eoscostarica.io, pull requests merged in 2022-07, with the labels that each got.

#478 feat(common): PoWvsPoSvsDPoS #449
  docs/eos-learn/consensus-mechanism.md
  docs/tools/pow-vs-pos-vs-dpos.md
  package.json
  sidebars.js
Labels: english

#477 Adding to developer guidelines ipfs investigation
  docs/interplanetary-file-system.md
  sidebars.js
Labels: documentation, english

#482 feat(common): Add information above consensus mechanims #480
  docs/consensus-mechanisms-blockchain.md
  sidebars.js
Labels: english

#487 feat(frontend): Add information about Blue Papers #385
  docs/eos-learn/eos-network-foundation.md
  sidebars.js
Labels: English and Spanish

#499 feat(frontend): Adding useful link ENG #495 and #500
  docs/community-resources/useful-links.md
  docs/eos-learn/smart-contracts.md
  docs/tools/example-eosio-smart-contract.md
  sidebars.js
Labels: English and Spanish

#491 docs(frontend): check titles for relevance
  docs/agile-methodologies.md
  docs/boilerplate.md
  docs/community-resources/blog-posts.md
  docs/community-resources/eos-podcasts.md
  docs/community-resources/eosio-networks.md
  docs/community-resources/telegram-channels.md
  docs/community-resources/useful-links.md
  docs/consensus-mechanisms-blockchain.md
  docs/developer-tools-ux-ui.md
  docs/developer-tools.md
  docs/devops.md
  docs/engineering-culture.md
  docs/eos-learn/accounts-and-permissions.md
  docs/eos-learn/block-producer.md
  docs/eos-learn/blockchain-security.md
  docs/eos-learn/consensus-mechanism.md
  docs/eos-learn/dapp-development.md
  docs/eos-learn/eos-blockchain.md
  docs/eos-learn/eosio-components.md
  docs/eos-learn/eosio-protocol.md
  docs/eos-learn/important-functions.md
  docs/eos-learn/migration-to-mandel.md
  docs/eos-learn/nft-on-eosio.mdx
  docs/eos-learn/private-keys.md
  docs/eos-learn/ricardian-contracts.md
  docs/eos-learn/smart-contracts.md
  docs/eos-learn/system-resources.md
  docs/flight-methodology.md
  docs/interplanetary-file-system.md
  docs/material-ui.md
  docs/open-source-guidelines.md
  docs/open-source-projects.mdx
  docs/pair-mob-programming.md
  docs/social-media-guidelines.md
  docs/tools/block-explorers.md
  docs/tools/command-line.md
  docs/tools/eosio-sdk-libraries.md
  docs/tools/frequently-asked-questions.md
  docs/tools/glossary.md
  docs/tools/nodeos-command-line-reference.md
  docs/tools/readme-file-template-source-code.md
  docs/tools/readme-file-template.md
  docs/tools/sample-nodeos-configs.md
  docs/tutorials/docker.md
  docs/tutorials/github-guide.md
  docs/tutorials/github-keys.md
  docs/tutorials/graphql-tutorial.md
  docs/tutorials/hello-world-contract.md
  docs/tutorials/how-to-mint.mdx
  docs/tutorials/how-to-publish-packages.md
  docs/tutorials/kubernetes.md
  docs/tutorials/markdown-guide.md
  docs/tutorials/modern-cpp.md
  docs/tutorials/node-installation.md
  docs/tutorials/private-network-installation.md
  docs/tutorials/react-tutorial.md
  docs/tutorials/workflow-tutorial.md
  docs/visual-resources.md
  docs/web-app-boilerplate.md
Labels: english

#517 fix(bug): Change to correct function ENG #516
  docusaurus.config.js
  src/pages/index.js
Labels: English and Spanish

#521 fix(frontend): Adding trailingSlash #465 ENG
  docusaurus.config.js
Labels: English and Spanish

#527 refactor(frontend): new descriptive hyperlink ENG #523
  CONTRIBUTING.md
  docs/community-resources/blog-posts.md
  docs/consensus-mechanisms-blockchain.md
  docs/developer-tools.md
  docs/engineering-culture.md
  docs/eos-learn/dapp-development.md
  docs/eos-learn/eos-network-foundation.md
  docs/eos-learn/eosio-components.md
  docs/eos-learn/important-functions.md
  docs/eos-learn/ricardian-contracts.md
  docs/eos-learn/system-resources.md
  docs/material-ui.md
  docs/tools/frequently-asked-questions.md
  docs/tools/readme-file-template.md
  docs/tutorials/docker.md
  docs/tutorials/github-guide.md
  docs/tutorials/github-keys.md
  docs/tutorials/kubernetes.md
  docs/tutorials/markdown-guide.md
  docs/tutorials/node-installation.md
  docs/tutorials/private-network-installation.md
  docs/tutorials/react-tutorial.md
Labels: English and Spanish

#535 docs(frontend): add blog link to security page
  docs/eos-learn/blockchain-security.md
Labels: english

#533 feat(frontend): improve homepage
  src/css/homepage.css
  src/pages/articleSection/CustomCard.js
  src/pages/articleSection/index.js
  src/pages/heroSection/ImagesCarousel.js
  src/pages/heroSection/index.js
  src/pages/index.js
  src/pages/startResource/CustomCard.js
  src/pages/startResource/index.js
  static/img/cards-icons/EOS-Previews-2.webp
  static/img/cards-icons/Hero-1.webp
  static/img/cards-icons/Hero-2.webp
  static/img/cards-icons/blog1.webp
  static/img/cards-icons/blog2.webp
  static/img/cards-icons/blog3.webp
  static/img/cards-icons/community.svg
  static/img/cards-icons/guidelines.svg
  static/img/cards-icons/icons-eosio.svg
  static/img/cards-icons/icons-opensource.svg
  static/img/cards-icons/learneosio.svg
  static/img/cards-icons/tools.svg
  static/img/cards-icons/tutorials.svg
Labels: english

#543 revert: this commit revert ca8b836fbf4df7c34b6c172cc4107c869be6d9ab
  src/pages/articleSection/CustomCard.js
  src/pages/articleSection/index.js
  src/pages/heroSection/ImagesCarousel.js
  src/pages/heroSection/index.js
  src/pages/startResource/CustomCard.js
  src/pages/startResource/index.js
Labels: english

#547 refactor(Homepage): New heroSection images ENG #546
  static/img/cards-icons/Hero-1.webp
  static/img/cards-icons/Hero-2.webp
  static/img/cards-icons/Hero-3.webp
Labels: english

#538 fix(frontend): resolve errors in markdown files
  docs/agile-methodologies.md
  docs/community-resources/eosio-networks.md
  docs/developer-tools-ux-ui.md
  docs/developer-tools.md
  docs/devops.md
  docs/eos-learn/accounts-and-permissions.md
  docs/eos-learn/block-producer.md
  docs/eos-learn/blockchain-security.md
  docs/eos-learn/consensus-mechanism.md
  docs/eos-learn/dapp-development.md
  docs/eos-learn/eos-blockchain.md
  docs/eos-learn/nft-on-eosio.mdx
  docs/eos-learn/smart-contracts.md
  docs/eos-learn/system-resources.md
  docs/flight-methodology.md
  docs/interplanetary-file-system.md
  docs/open-source-guidelines.md
  docs/open-source-projects.mdx
  docs/pair-mob-programming.md
  docs/tutorials/hello-world-contract.md
  docs/tutorials/markdown-guide.md
  docs/tutorials/modern-cpp.md
  docs/tutorials/react-tutorial.md
  docs/tutorials/workflow-tutorial.md
  src/components/ProjectContainer/DisplayImages.js
Labels: english
